services:
  server_a:
    build:
      context: .
      dockerfile: Dockerfile.server_a
    environment:
      - TARGET_VAR=special_value
    depends_on:
      - server_b

  server_b:
    build:
      context: .
      dockerfile: Dockerfile.server_b
    ports:
      - "8001:8000"
